config/routes.rb
Association::Application.routes.draw do
  resources :positons

  resources :employees

  resources :only_layout_fluids

  resources :only_layouts

  resources :offices

  resources :products

  get "home/index"
  devise_for :users

  root 'offices#index'

end

app/models/positon.rb
class Positon < ActiveRecord::Base
	has_many :offices
	def to_s
		self.work_position
	end
end

app/controllers/positons_controller.rb
class PositonsController < ApplicationController
  before_action :set_positon, only: [:show, :edit, :update, :destroy]

  # GET /positons
  # GET /positons.json
  def index
    @positons = Positon.all
  end

  # GET /positons/1
  # GET /positons/1.json
  def show
  end

  # GET /positons/new
  def new
    @positon = Positon.new
  end

  # GET /positons/1/edit
  def edit
  end

  # POST /positons
  # POST /positons.json
  def create
    @positon = Positon.new(positon_params)

    respond_to do |format|
      if @positon.save
        format.html { redirect_to @positon, notice: 'Positon was successfully created.' }
        format.json { render action: 'show', status: :created, location: @positon }
      else
        format.html { render action: 'new' }
        format.json { render json: @positon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /positons/1
  # PATCH/PUT /positons/1.json
  def update
    respond_to do |format|
      if @positon.update(positon_params)
        format.html { redirect_to @positon, notice: 'Positon was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @positon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /positons/1
  # DELETE /positons/1.json
  def destroy
    @positon.destroy
    respond_to do |format|
      format.html { redirect_to positons_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_positon
      @positon = Positon.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def positon_params
      params.require(:positon).permit(:work_position)
    end
end

app/helpers/positons_helper.rb
module PositonsHelper
end

app/views/positons/_form.html.erb
<%= simple_form_for(@positon) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :work_position %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/positons/edit.html.erb
<h1>Editing positon</h1>

<%= render 'form' %>

<%= link_to 'Show', @positon %> |
<%= link_to 'Back', positons_path %>

app/views/positons/index.html.erb
<h1>Listing positons</h1>

<table>
  <thead>
    <tr>
      <th>Work position</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @positons.each do |positon| %>
      <tr>
        <td><%= positon.work_position %></td>
        <td><%= link_to 'Show', positon %></td>
        <td><%= link_to 'Edit', edit_positon_path(positon) %></td>
        <td><%= link_to 'Destroy', positon, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Positon', new_positon_path %>

app/views/positons/new.html.erb
<h1>New positon</h1>

<%= render 'form' %>

<%= link_to 'Back', positons_path %>

app/views/positons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Work position:</strong>
  <%= @positon.work_position %>
</p>

<%= link_to 'Edit', edit_positon_path(@positon) %> |
<%= link_to 'Back', positons_path %>