config/routes.rb
Association::Application.routes.draw do
  resources :positons

  resources :employees

  resources :only_layout_fluids

  resources :only_layouts

  resources :offices

  resources :products

  get "home/index"
  devise_for :users

  root 'offices#index'

end

app/models/only_layout.rb
class OnlyLayout < ActiveRecord::Base
end

app/controllers/only_layouts_controller.rb
class OnlyLayoutsController < ApplicationController
  before_action :set_only_layout, only: [:show, :edit, :update, :destroy]

  # GET /only_layouts
  # GET /only_layouts.json
  def index
    @only_layouts = OnlyLayout.all
  end

  # GET /only_layouts/1
  # GET /only_layouts/1.json
  def show
  end

  # GET /only_layouts/new
  def new
    @only_layout = OnlyLayout.new
  end

  # GET /only_layouts/1/edit
  def edit
  end

  # POST /only_layouts
  # POST /only_layouts.json
  def create
    @only_layout = OnlyLayout.new(only_layout_params)

    respond_to do |format|
      if @only_layout.save
        format.html { redirect_to @only_layout, notice: 'Only layout was successfully created.' }
        format.json { render action: 'show', status: :created, location: @only_layout }
      else
        format.html { render action: 'new' }
        format.json { render json: @only_layout.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /only_layouts/1
  # PATCH/PUT /only_layouts/1.json
  def update
    respond_to do |format|
      if @only_layout.update(only_layout_params)
        format.html { redirect_to @only_layout, notice: 'Only layout was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @only_layout.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /only_layouts/1
  # DELETE /only_layouts/1.json
  def destroy
    @only_layout.destroy
    respond_to do |format|
      format.html { redirect_to only_layouts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_only_layout
      @only_layout = OnlyLayout.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def only_layout_params
      params.require(:only_layout).permit(:name, :age, :qualification, :description)
    end
end

app/helpers/only_layouts_helper.rb
module OnlyLayoutsHelper
end

app/views/only_layouts/_form.html.erb
<%= simple_form_for(@only_layout) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :age %>
    <%= f.input :qualification %>
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/only_layouts/edit.html.erb
<h1>Editing only_layout</h1>

<%= render 'form' %>

<%= link_to 'Show', @only_layout %> |
<%= link_to 'Back', only_layouts_path %>

app/views/only_layouts/index.html.erb
<h1>Listing only_layouts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Qualification</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @only_layouts.each do |only_layout| %>
      <tr>
        <td><%= only_layout.name %></td>
        <td><%= only_layout.age %></td>
        <td><%= only_layout.qualification %></td>
        <td><%= only_layout.description %></td>
        <td><%= link_to 'Show', only_layout %></td>
        <td><%= link_to 'Edit', edit_only_layout_path(only_layout) %></td>
        <td><%= link_to 'Destroy', only_layout, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Only layout', new_only_layout_path %>

app/views/only_layouts/new.html.erb
<h1>New only_layout</h1>

<%= render 'form' %>

<%= link_to 'Back', only_layouts_path %>

app/views/only_layouts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @only_layout.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @only_layout.age %>
</p>

<p>
  <strong>Qualification:</strong>
  <%= @only_layout.qualification %>
</p>

<p>
  <strong>Description:</strong>
  <%= @only_layout.description %>
</p>

<%= link_to 'Edit', edit_only_layout_path(@only_layout) %> |
<%= link_to 'Back', only_layouts_path %>