config/routes.rb
Association::Application.routes.draw do
  resources :positons

  resources :employees

  resources :only_layout_fluids

  resources :only_layouts

  resources :offices

  resources :products

  get "home/index"
  devise_for :users

  root 'offices#index'

end

app/models/only_layout_fluid.rb
class OnlyLayoutFluid < ActiveRecord::Base
end

app/controllers/only_layout_fluids_controller.rb
class OnlyLayoutFluidsController < ApplicationController
  before_action :set_only_layout_fluid, only: [:show, :edit, :update, :destroy]

  # GET /only_layout_fluids
  # GET /only_layout_fluids.json
  def index
    @only_layout_fluids = OnlyLayoutFluid.all
  end

  # GET /only_layout_fluids/1
  # GET /only_layout_fluids/1.json
  def show
  end

  # GET /only_layout_fluids/new
  def new
    @only_layout_fluid = OnlyLayoutFluid.new
  end

  # GET /only_layout_fluids/1/edit
  def edit
  end

  # POST /only_layout_fluids
  # POST /only_layout_fluids.json
  def create
    @only_layout_fluid = OnlyLayoutFluid.new(only_layout_fluid_params)

    respond_to do |format|
      if @only_layout_fluid.save
        format.html { redirect_to @only_layout_fluid, notice: 'Only layout fluid was successfully created.' }
        format.json { render action: 'show', status: :created, location: @only_layout_fluid }
      else
        format.html { render action: 'new' }
        format.json { render json: @only_layout_fluid.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /only_layout_fluids/1
  # PATCH/PUT /only_layout_fluids/1.json
  def update
    respond_to do |format|
      if @only_layout_fluid.update(only_layout_fluid_params)
        format.html { redirect_to @only_layout_fluid, notice: 'Only layout fluid was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @only_layout_fluid.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /only_layout_fluids/1
  # DELETE /only_layout_fluids/1.json
  def destroy
    @only_layout_fluid.destroy
    respond_to do |format|
      format.html { redirect_to only_layout_fluids_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_only_layout_fluid
      @only_layout_fluid = OnlyLayoutFluid.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def only_layout_fluid_params
      params.require(:only_layout_fluid).permit(:name, :age, :qualification, :description)
    end
end

app/helpers/only_layout_fluids_helper.rb
module OnlyLayoutFluidsHelper
end

app/views/only_layout_fluids/_form.html.erb
<%= simple_form_for(@only_layout_fluid) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :age %>
    <%= f.input :qualification %>
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/only_layout_fluids/edit.html.erb
<h1>Editing only_layout_fluid</h1>

<%= render 'form' %>

<%= link_to 'Show', @only_layout_fluid %> |
<%= link_to 'Back', only_layout_fluids_path %>

app/views/only_layout_fluids/index.html.erb
<h1>Listing only_layout_fluids</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Qualification</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @only_layout_fluids.each do |only_layout_fluid| %>
      <tr>
        <td><%= only_layout_fluid.name %></td>
        <td><%= only_layout_fluid.age %></td>
        <td><%= only_layout_fluid.qualification %></td>
        <td><%= only_layout_fluid.description %></td>
        <td><%= link_to 'Show', only_layout_fluid %></td>
        <td><%= link_to 'Edit', edit_only_layout_fluid_path(only_layout_fluid) %></td>
        <td><%= link_to 'Destroy', only_layout_fluid, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Only layout fluid', new_only_layout_fluid_path %>

app/views/only_layout_fluids/new.html.erb
<h1>New only_layout_fluid</h1>

<%= render 'form' %>

<%= link_to 'Back', only_layout_fluids_path %>

app/views/only_layout_fluids/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @only_layout_fluid.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @only_layout_fluid.age %>
</p>

<p>
  <strong>Qualification:</strong>
  <%= @only_layout_fluid.qualification %>
</p>

<p>
  <strong>Description:</strong>
  <%= @only_layout_fluid.description %>
</p>

<%= link_to 'Edit', edit_only_layout_fluid_path(@only_layout_fluid) %> |
<%= link_to 'Back', only_layout_fluids_path %>